spring:
  application:
    name: notr
  datasource:
    url: jdbc:mysql://root:CyZZrcHwfLLftVJUxmwQuvLOqoSpDjIf@mysql.railway.internal:3306/railway
    username: root
    password: CyZZrcHwfLLftVJUxmwQuvLOqoSpDjIf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
