spring:
  application:
    name: notr
  datasource:
    url: jdbc:${{ MySQL.MYSQL_URL }}
    username: ${{MySQL.MYSQLUSER}}
    password: ${{MySQL.MYSQL_ROOT_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true